# Generated by Django 5.1.1 on 2024-10-10 06:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('penjual', '0002_penjual_rename_prodi_pelanggan'),
    ]

    operations = [
        migrations.DeleteModel(
            name='pelanggan',
        ),
        migrations.DeleteModel(
            name='penjual',
        ),
    ]
