# Generated by Django 5.1.1 on 2024-10-10 06:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produk', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='produk',
        ),
    ]
