# Generated by Django 5.1.1 on 2024-10-09 03:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pelanggan', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='penjual',
        ),
    ]
