# Generated by Django 5.1.1 on 2024-10-10 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0002_penjual_pesanan_produk_delete_master_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='detail_pesanan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_produk', models.CharField(max_length=5)),
                ('harga_subtotal', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='keranjang_belanja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_produk', models.CharField(max_length=5)),
                ('harga_subtotal', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='pengiriman',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100)),
                ('kode', models.CharField(max_length=5, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='review_produk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deskripsi', models.CharField()),
            ],
        ),
        migrations.AlterField(
            model_name='penjual',
            name='id_seller',
            field=models.CharField(max_length=5),
        ),
        migrations.AlterField(
            model_name='penjual',
            name='nama_toko',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
