# Generated by Django 5.1.1 on 2024-10-10 06:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('review_produk', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='review_produk',
        ),
    ]
